import React from 'react'

const Menu = [
    {   
        id:1,
        name:"Maggie",
        image:'./images/maggie.jpeg',
        category:"Evening",
        description:"Tasty and very very tasty maggie made in butter",
        price:"25₹",
    },
    {   
        id:2,
        name:"Burger",
        image:'./images/burger.jpeg',
        category:"Evening",
        description:"Tasty and very very tasty maggie made in butter",
        price:"50₹",
    },
    {   
        id:3,
        name:"Pizza",
        image:'./images/pizza.jpeg',
        category:"Dinner",
        description:"Tasty and very very tasty maggie made in butter",
        price:"125₹",
    },
    {   
        id:4,
        name:"Poha",
        image:'./images/poha.jpeg',
        category:"Breakfast",
        description:"Tasty and very very tasty maggie made in butter",
        price:"30₹",
    },
    {   
        id:5,
        name:"Paratha",
        image:'./images/paratha.jpeg',
        category:"Dinner",
        description:"Tasty and very very tasty maggie made in butter",
        price:"25₹",
    },
    {   
        id:6,
        name:"Soup",
        image:'./images/soup.jpeg',
        category:"Dinner",
        description:"Tasty and very very tasty maggie made in butter",
        price:"50₹",
    },
    {   
        id:7,
        name:"Dosa",
        image:'./images/dosa.jpeg',
        category:"Breakfast",
        description:"Tasty and very very tasty maggie made in butter",
        price:"50₹",
    },
    {   
        id:8,
        name:"Momo",
        image:'./images/momos.jpeg',
        category:"Evening",
        description:"Tasty and very very tasty maggie made in butter",
        price:"60₹",
    },
    {   
        id:9,
        name:"Biryani",
        image:'./images/biryani.jpeg',
        category:"Lunch",
        description:"Tasty and very very tasty maggie made in butter",
        price:"125₹",
    },
    {   
        id:10,
        name:"Poori Sabji",
        image:'./images/poorisabji.jpeg',
        category:"Lunch",
        description:"Tasty and very very tasty maggie made in butter",
        price:"60₹",
    },
    {   
        id:11,
        name:"Idali",
        image:'./images/maggie.jpeg',
        category:"Breakfast",
        description:"Tasty and very very tasty maggie made in butter",
        price:"60₹",
    },
    {   
        id:12,
        name:"Cutlet",
        image:'./images/cutlet.jpeg',
        category:"Breakfast",
        description:"Tasty and very very tasty maggie made in butter",
        price:"50₹",
    },
    {   
        id:13,
        name:"Kadhai Paneer",
        image:'./images/kadhaipaneer.jpeg',
        category:"Dinner",
        description:"Tasty and very very tasty maggie made in butter",
        price:"90₹",
    },
    {   
        id:14,
        name:"Chapati Daal",
        image:'./images/chapatidaal.jpeg',
        category:"Dinner",
        description:"Tasty and very very tasty maggie made in butter",
        price:"95₹",
    },
    {   
        id:15,
        name:"Golgappe",
        image:'./images/golgappe.jpeg',
        category:"Evening",
        description:"Tasty and very very tasty maggie made in butter",
        price:"35₹",
    },
]

export default Menu
